### ISSUE TITLE
Migration issue with Django 1.7.8

### ISSUE THREAD

**Issue by rev112** [Bouke/django-two-factor-auth#101]
I'm trying to use `django-two-factor-auth` in my project, but when I run 
`$ python3 manage.py makemigrations`
 here's what I get:
```
Migrations for 'two_factor':
  0003_auto_20150605_1541.py:
    - Alter field confirmed on phonedevice
    - Alter field key on phonedevice
    - Alter field method on phonedevice
    - Alter field name on phonedevice
    - Alter field number on phonedevice
    - Alter field user on phonedevice
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/makemigrations.py", line 124, in handle
    self.write_migration_files(changes)
  File "/usr/local/lib/python3.4/dist-packages/django/core/management/commands/makemigrations.py", line 153, in write_migration_files
    with open(writer.path, "wb") as fh:
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.4/dist-packages/two_factor/migrations/0003_auto_20150605_1541.py'
```

Python 3.4.0
Django 1.7.8
django-two-factor-auth 1.2.0

**Comment by Bouke** [comment]
First of all, you shouldn't be creating migrations for apps outside of your control, like `two_factor`. Django will try to write to a read-only location, and the PermissionError will throw.

Furthermore, something is off with your installation as Django doesn't list any changes for me (also on 1.7.8).

    $ python example/manage.py makemigrations two_factor
    No changes detected in app 'two_factor'
