### ISSUE TITLE
KeyError when trying to login

### ISSUE THREAD

**Issue by Bouke** [Bouke/django-two-factor-auth#102]
Seen on the hosted example:

    Internal Server Error: /account/login/
    Traceback (most recent call last):
      File "/django/core/handlers/base.py", line 132, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/django/views/generic/base.py", line 71, in view
        return self.dispatch(request, *args, **kwargs)
      File "/django/utils/decorators.py", line 34, in _wrapper
        return bound_func(*args, **kwargs)
        return view(request, *args, **kwargs)
      File "/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
        return func.__get__(self, type(self))(*args2, **kwargs2)
        return bound_func(*args, **kwargs)
      File "/django/views/decorators/cache.py", line 57, in _wrapped_view_func
        response = view_func(request, *args, **kwargs)
      File "/django/utils/decorators.py", line 30, in bound_func
      File "/django/utils/decorators.py", line 34, in _wrapper
        return func.__get__(self, type(self))(*args2, **kwargs2)
      File "/django/utils/decorators.py", line 30, in bound_func
      File "/formtools/wizard/views.py", line 237, in dispatch
        response = super(WizardView, self).dispatch(request, *args, **kwargs)
      File "/django/views/generic/base.py", line 89, in dispatch
        return handler(request, *args, **kwargs)
      File "/two_factor/views/core.py", line 94, in post
      File "/two_factor/views/utils.py", line 123, in post
        return super(LoginView, self).post(*args, **kwargs)
        return super(IdempotentSessionWizardView, self).post(*args, **kwargs)
      File "/formtools/wizard/views.py", line 300, in post
      File "/two_factor/views/utils.py", line 174, in render_done
        return self.render_done(form, **kwargs)
        self.storage.reset()
      File "/formtools/wizard/storage/base.py", line 34, in reset
        wizard_files = self.data[self.step_files_key]
      File "/formtools/wizard/storage/session.py", line 13, in _get_data
        return self.request.session[self.prefix]
      File "/django/contrib/sessions/backends/base.py", line 48, in __getitem__
        return self._session[key]
    KeyError: 'wizard_login_view'

**Comment by mohsinhijazee** [comment]
I am also having the same issue. Is this resolve or any workaround for it?

**Comment by timfeirg** [comment]
I occasionally bump into this issue, refresh page usually fix it

**Comment by Bouke** [comment]
I'm not quite sure how to reproduce the issue, maybe it is related to the browser doing a prefetch?

**Comment by sbrandtb** [comment]
I can reliably reproduce it on my django 1.8 installation:

 * log out
 * access some admin page
 * the admin login page shows up
 * log in with some *not permitted* user -> the login page shows again, as if nothing happened
 * log in in with a permitted user
 * -> the error shows up

I'm now trying to track this down, but maybe this description helps someone else, too.

**Comment by epalm** [comment]
I'm experiencing and can reproduce the same issue, as described by @sbrandtb

**Comment by vvojvoda** [comment]
To add to comment by @sbrandtb, this seems to happen each time you try to login a user, when another user is already logged in when trying to restore the session. Checking if ExtraSessionStorage.prefix exists in session before trying to reset the session seems to resolve this issue.
I've submitted a commit that seems to resolve this, and although the tests pass, I'm not sure if this is the right way to handle this, and what the side effects may be.
