### ISSUE TITLE
patch_admin fails on django 1.9

### ISSUE THREAD

**Issue by fgaudin** [Bouke/django-two-factor-auth#130]
Using master:

(p3)vagrant@vagrant-ubuntu-trusty-64:/auth$ ./manage.py shell
Traceback (most recent call last):
  File "./manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/home/vagrant/p3/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/vagrant/p3/lib/python3.4/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "/home/vagrant/p3/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/p3/lib/python3.4/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/vagrant/p3/lib/python3.4/site-packages/django/apps/config.py", line 116, in create
    mod = import_module(mod_path)
  File "/home/vagrant/p3/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/home/vagrant/p3/src/two-factor/two_factor/apps.py", line 4, in <module>
    from .admin import patch_admin
  File "/home/vagrant/p3/src/two-factor/two_factor/admin.py", line 12, in <module>
    from .utils import monkeypatch_method
  File "/home/vagrant/p3/src/two-factor/two_factor/utils.py", line 1, in <module>
    from two_factor.models import PhoneDevice
  File "/home/vagrant/p3/src/two-factor/two_factor/models.py", line 8, in <module>
    from django_otp.models import Device
  File "/home/vagrant/p3/lib/python3.4/site-packages/django_otp/models.py", line 31, in <module>
    class Device(models.Model):
  File "/home/vagrant/p3/lib/python3.4/site-packages/django/db/models/base.py", line 94, in __new__
    app_config = apps.get_containing_app_config(module)
  File "/home/vagrant/p3/lib/python3.4/site-packages/django/apps/registry.py", line 239, in get_containing_app_config
    self.check_apps_ready()
  File "/home/vagrant/p3/lib/python3.4/site-packages/django/apps/registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.

**Comment by aaugustin** [comment]
#131 fixes this problem.

**Comment by Bouke** [comment]
#131 has been merged now, thanks @fgaudin for reporting and @aaugustin for the fix!
