### ISSUE TITLE
No module "user_sessions"

### ISSUE THREAD

**Issue by fizista** [Bouke/django-two-factor-auth#143]
No module user_sessions in the sample site.

`
> make example
Traceback (most recent call last):
  File "/home/.../site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/.../site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/home/.../site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/.../site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/.../site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/.../site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/.../site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/.../site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/home/.../lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2224, in _find_and_load_unlocked
ImportError: No module named 'user_sessions'
`

**Comment by fizista** [comment]
My mistake ;)

I forgot to install depending on the development.

**Comment by allcaps** [comment]
install django-user-sessions
