### ISSUE TITLE
`make test` fails on invalid OTP token

### ISSUE THREAD

**Issue by guillaumepiot** [Bouke/django-two-factor-auth#174]
After running the package under its own venv and installed the dev requirements, the test command is still failing over the OTP token. I'm not sure if I'm missing something in the installation but here's the error log I get:

```
======================================================================
FAIL: test_with_backup_token (tests.test_views_login.LoginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/mock.py", line 1157, in patched
    return func(*args, **keywargs)
  File "/Users/guillaumepiot/Documents/Projects/packages/two_factor/django-two-factor-auth/tests/test_views_login.py", line 170, in test_with_backup_token
    self.assertContains(response, 'Please enter your OTP token')
  File "/Users/guillaumepiot/Documents/Projects/packages/two_factor/venv/lib/python3.5/site-packages/django/test/testcases.py", line 382, in assertContains
    self.assertTrue(real_count != 0, msg_prefix + "Couldn't find %s in response" % text_repr)
AssertionError: False is not true : Couldn't find 'Please enter your OTP token' in response

======================================================================
FAIL: test_with_generator (tests.test_views_login.LoginTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/unittest/mock.py", line 1157, in patched
    return func(*args, **keywargs)
  File "/Users/guillaumepiot/Documents/Projects/packages/two_factor/django-two-factor-auth/tests/test_views_login.py", line 80, in test_with_generator
    {'__all__': ['Please enter your OTP token']})
AssertionError: {'__all__': ['Invalid token. Please make sure you have entered it correctly.']} != {'__all__': ['Please enter your OTP token']}
```

**Comment by Bouke** [comment]
I'm not quite sure why the error message changed, but it's resolved in e9a009f15d57af995c29ae1bdee087c09c2c0338.
