### ISSUE TITLE
Exception on startup if `django.contrib.admin` not in INSTALLED_APPS

### ISSUE THREAD

**Issue by spookylukey** [Bouke/django-two-factor-auth#297]
Steps to reproduce:

Install two-factor-auth into a fresh virtualenv:

    $ mkvirtualenv --python=`which python3.6` d2fa_pr296_test
    $ pip install django-two-factor-auth

Start a project:

    $ django-admin.py startproject pr296_test
    $ cd pr296_test

Edit the generated settings.py and modify `INSTALLED_APPS`:
* Add the two_factor/django-otp apps as per https://django-two-factor-auth.readthedocs.io/en/stable/installation.html
* remove `'django.contrib.admin'`

* Add `TWO_FACTOR_PATCH_ADMIN = False` to settings.py

Also remove 'admin' line from generated urls.py

Open a shell with manage.py:

     $ ./manage.py shell           
    Traceback (most recent call last):
      File "/home/luke/.virtualenvs/d2fa_pr296_test/lib/python3.6/site-packages/django/apps/registry.py", line 155, in get_app_config
        return self.app_configs[app_label]
    KeyError: 'admin'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "./manage.py", line 21, in <module>
        main()
      File "./manage.py", line 17, in main
        execute_from_command_line(sys.argv)
      File "/home/luke/.virtualenvs/d2fa_pr296_test/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
        utility.execute()
      File "/home/luke/.virtualenvs/d2fa_pr296_test/lib/python3.6/site-packages/django/core/management/__init__.py", line 357, in execute
        django.setup()
      File "/home/luke/.virtualenvs/d2fa_pr296_test/lib/python3.6/site-packages/django/__init__.py", line 24, in setup
        apps.populate(settings.INSTALLED_APPS)
      File "/home/luke/.virtualenvs/d2fa_pr296_test/lib/python3.6/site-packages/django/apps/registry.py", line 122, in populate
        app_config.ready()
      File "/home/luke/.virtualenvs/d2fa_pr296_test/lib/python3.6/site-packages/two_factor/apps.py", line 10, in ready
        from .admin import patch_admin
      File "/home/luke/.virtualenvs/d2fa_pr296_test/lib/python3.6/site-packages/two_factor/admin.py", line 78, in <module>
        admin.site.register(PhoneDevice, PhoneDeviceAdmin)
      File "/home/luke/.virtualenvs/d2fa_pr296_test/lib/python3.6/site-packages/django/utils/functional.py", line 256, in inner
        self._setup()
      File "/home/luke/.virtualenvs/d2fa_pr296_test/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 529, in _setup
        AdminSiteClass = import_string(apps.get_app_config('admin').default_site)
      File "/home/luke/.virtualenvs/d2fa_pr296_test/lib/python3.6/site-packages/django/apps/registry.py", line 162, in get_app_config
        raise LookupError(message)
    LookupError: No installed app with label 'admin'.

If I change the two_factor code as per #296 then the problem goes away.

**Comment by moggers87** [comment]
This seems to be have been a change in Django 2.1, it works fine in 1.11 and 2.0. Thanks for the report!

**Comment by claudep** [comment]
As the patch has been merged, I guess we can close this issue.

**Comment by moggers87** [comment]
Fixed by #296
