### ISSUE TITLE
Login broken... X-Frame-Options / AttributeError

### ISSUE THREAD

**Issue by RyanHope** [Bouke/django-two-factor-auth#322]
I had everything working last week, not sure what has updated since then but now my login page is broken. Everything else working.

```
Internal Server Error: /account/login/
Traceback (most recent call last):
  File "/mnt/data/workspace/website/website-env-local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/mnt/data/workspace/website/website-env-local/lib/python3.7/site-packages/django/utils/deprecation.py", line 96, in __call__
    response = self.process_response(request, response)
  File "/mnt/data/workspace/website/website-env-local/lib/python3.7/site-packages/django/middleware/clickjacking.py", line 26, in process_response
    if response.get('X-Frame-Options') is not None:
AttributeError: 'function' object has no attribute 'get'
```

**Comment by moggers87** [comment]
Some more information would be nice, e.g.

* Browser and version:
* Python version:
* Django version:
* django-otp version:
* django-two-factor-auth version:

Also does the error go away if you comment out the clickjacking middleware?

**Comment by RyanHope** [comment]
Working on finding more meaning debug info than what I am getting now. If I comment out the clickjacking middleware the bug moves. I can also run the example website and login works there.
