### ISSUE TITLE
Validator in migration `0001_initial` breaks `makemigrations` command (Python 3)

### ISSUE THREAD

**Issue by valberg** [Bouke/django-two-factor-auth#87]
Running `./manage.py makemigrations` on a project with `two_factor` in `INSTALLED_APPS` results in this error:

```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/valberg/.virtualenvs/myenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/valberg/.virtualenvs/myenv/lib/python3.4/site-packages/django/core/management/__init__.py", line 377, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/valberg/.virtualenvs/myenv/lib/python3.4/site-packages/django/core/management/base.py", line 288, in run_from_argv
    self.execute(*args, **options.__dict__)
  File "/Users/valberg/.virtualenvs/myenv/lib/python3.4/site-packages/django/core/management/base.py", line 338, in execute
    output = self.handle(*args, **options)
  File "/Users/valberg/.virtualenvs/myenv/lib/python3.4/site-packages/django/core/management/commands/makemigrations.py", line 111, in handle
    convert_apps=app_labels or None,
  File "/Users/valberg/.virtualenvs/myenv/lib/python3.4/site-packages/django/db/migrations/autodetector.py", line 42, in changes
    changes = self._detect_changes(convert_apps, graph)
  File "/Users/valberg/.virtualenvs/myenv/lib/python3.4/site-packages/django/db/migrations/autodetector.py", line 184, in _detect_changes
    self.generate_altered_fields()
  File "/Users/valberg/.virtualenvs/myenv/lib/python3.4/site-packages/django/db/migrations/autodetector.py", line 870, in generate_altered_fields
    if old_field_dec != new_field_dec:
  File "/Users/valberg/.virtualenvs/myenv/lib/python3.4/site-packages/django/core/validators.py", line 57, in __eq__
    self.regex.pattern == other.regex.pattern and
AttributeError: 'bytes' object has no attribute 'pattern'
```

This is due to line 22 in `two_factor/migrations/0001_initial.py` where the regex is `b'^(\\+|00)'` - this should probably be `r'^(\\+|00)'` instead.

**Comment by Bouke** [comment]
Could you test your change? The migration was auto-created by Django. Maybe could you also try removing the migrations and re-create them using Python 3, and compare them with the ones included with the package?
